import pt from './pt-BR';
const en = {...pt,
  'nav.logoLabel':'Go to Rikka home page','theme.label':'Theme','sticker.drop':'NEW DROP!','sticker.wanted':'WANTED ♡','sticker.plusOne':'+1 CARD','sticker.gotIt':'GOT IT!','rikkaNote.label':'Rikka says:','rikkaNote.drop':'Could your favorite be in the next drop? ♡','rikkaNote.collection':'This one goes in the collection!',
  'nav.label':'Main navigation','nav.home':'Home','nav.how':'How it works','nav.collection':'Collection','nav.features':'Features','nav.about':'About','nav.login':'Log in','nav.add':'Add to Discord','nav.open':'Open menu','nav.close':'Close menu','lang.label':'Language','theme.dark':'Enable dark mode','theme.light':'Enable light mode','theme.nameLight':'Light','theme.nameDark':'Dark','skip':'Skip to content',
  'common.ready':'Ready to start?','common.add':'Add Rikka','common.addDiscord':'Add to Discord','common.support':'Support server','common.next':'Your next card could be in the next drop.','common.nextText':'Add Rikka to your server and start your collection.','common.cardsNote':'Illustrative cards — actual artwork appears on Discord.','common.avatar':'Rikka official avatar',
  'home.seo.title':'Rikka — Discord Card Collection Bot','home.seo.description':'Collect anime and game characters, discover different editions, and build your collection with Rikka on Discord.','home.kicker':'Anime and game cards on Discord','home.title':'Your favorite characters.','home.accent':'Your collection.','home.text':'Discover anime and game characters, claim cards from drops, and build a collection that is truly yours — right on Discord.','home.howCta':'See how it works','home.hello':'Meet Rikka!','home.intro':'A card collection bot for Discord.','home.introText':'Pick your favorite characters, discover different editions, and build a unique collection without leaving your server.','home.dreamsText':'Rikka was created to make character collecting more fun on Discord.','home.aboutCta':'Meet Rikka',
  'flow.kicker':'Easy to get started','flow.title':'How it works','flow.subtitle':'From chat to your collection in three steps.','flow.dropText':'Rikka presents three cards in the chat.','flow.grabText':'Choose yours before anyone else.','flow.collection':'Collection','flow.collectionText':'The card joins your collection.','flow.cta':'See how it works',
  'drop.title':'A drop appears.','drop.text':'Three cards arrive in a Discord channel. A quick moment of luck, surprise, and choosing before anyone else.','drop.message':'A new drop appeared! Choose a card before someone else does.','grab.title':'Choose yours.','grab.text':'Found a card that belongs in your collection? Claim it, get instant confirmation, and watch for the next drop.','grab.fast':'Quick choice','grab.feedback':'Instant feedback','grab.message':'Great choice! This card is now part of your collection.','grab.toast':'Card B added to your collection','mock.now':'now',
  'collection.kicker':'Your collection','collection.title':'Build your collection.','collection.text':'Every grab adds to your story. Gather characters, organize your favorite cards, and watch your collection grow.','collection.deck':'YOUR DECK','collection.unique':'unique and entirely yours','collection.cta':'Explore the collection','collection.card':'Card','editions.kicker':'More to discover','editions.title':'The same character.','editions.accent':'Different editions.','editions.text':'Find variations, discover new looks, and expand every part of your collection.','editions.item':'Edition',
  'resources.kicker':'For true completionists','resources.title':'Collect with purpose.','resources.cta':'See all features','wishlist.title':'Find the cards you truly want.','wishlist.text':'Keep track of wanted characters and editions so you always know what to look for next.','wishlist.item':'Special edition','wishlist.state':'On your list','trade.title':'Trade. Complete your collection. Keep collecting.','trade.text':'Offer cards, receive new ones, and get closer to the collection you imagined.','supportTools.label':'Currency & items','supportTools.title':'Resources that support your collection.','supportTools.text':'Items and currency support your collecting journey without taking the focus away from the cards.',
  'how.seo.title':'How It Works | Rikka','how.seo.description':'Learn how drops, grabs, and collections work in Rikka, a Discord card collection bot.','how.hero.kicker':'The core experience','how.hero.title':'How it works','how.hero.accent':'From a drop to your collection.','how.hero.text':'Rikka turns three simple steps into the heart of your collection on Discord.','how.cta.title':'Ready to start?','how.cta.text':'Add Rikka and wait for your first drop.',
  'collectionPage.seo.title':'Card Collection | Rikka','collectionPage.seo.description':'Build your character collection, discover different editions, track your wishlist, and complete your deck with Rikka.','collectionPage.hero.kicker':'Characters, cards, and editions','collectionPage.hero.title':'Your collection.','collectionPage.hero.accent':'Your way.','collectionPage.hero.text':'Gather your favorite characters, discover different editions, and watch your deck grow with every grab.','collectionPage.cta.title':'Keep collecting.','collectionPage.cta.text':'The next drop might have exactly the card you are missing.',
  'featuresPage.seo.title':'Features | Rikka','featuresPage.seo.description':'Explore the wishlist, trades, currency, and items that help you complete your collection with Rikka.','featuresPage.hero.kicker':'Support for every collection','featuresPage.hero.title':'Features that help','featuresPage.hero.accent':'your collection.','featuresPage.hero.text':'Wishlist, trades, currency, and items keep your search organized without taking the focus away from cards.','journey.want':'Wish','journey.wantText':'Save what you are looking for.','journey.trade':'Trade','journey.tradeText':'Move your collection forward.','journey.complete':'Complete','journey.completeText':'Get closer to your perfect deck.',
  'aboutPage.seo.title':'About Rikka | Discord Collection Bot','aboutPage.seo.description':'Meet Rikka, a Dreams Experience project made for people who love collecting anime and game characters on Discord.','aboutPage.hero.kicker':'About Rikka','aboutPage.hero.title':'Made for people who love','aboutPage.hero.accent':'collecting.','aboutPage.hero.text':'A project created to turn character collecting into a fun experience on Discord.','aboutPage.goal':'The goal','aboutPage.center':'Cards at the center of everything.','aboutPage.p1':'Rikka is a card collection bot featuring characters from anime and games. Drops, grabs, editions, wishlists, and trades make every collection personal and fun.','aboutPage.p2':'No unnecessary complexity: Rikka lives on Discord and helps you discover, choose, and collect the cards you really want.','aboutPage.dreamsTitle':'A Dreams Experience project.','aboutPage.dreamsText':'Rikka is part of Dreams Experience while keeping its own cheerful, collectible identity made for Discord.','aboutPage.dreamsCta':'Meet Dreams Experience',
  'footer.tagline':'Cards, characters, and collections.','footer.project':'Project','footer.legal':'Legal','footer.terms':'Terms','footer.privacy':'Privacy','footer.soon':'coming soon','footer.rights':'All rights reserved.','support.seo':'Support — Rikka','support.kicker':'We are here to help','support.title':'Need some help?','support.text':'Join Rikka’s support server and talk directly to the project team.','support.cta':'Join the server',
  'notFound.seoTitle':'Page not found | Rikka','notFound.kicker':'Lost card','notFound.title':"This card couldn't be found.",'notFound.text':"Looks like the page you're looking for doesn't exist — maybe this card slipped out of the collection.",'notFound.home':'Back to home','notFound.how':'How it works','notFound.sticker':'Where is it?','notFound.card':'Missing card','notFound.rikka':'Huh... I was sure there was a card here.','status.notFound':'Page not found or moved!','status.blocked':'Registration blocked','status.blockedText':'An account has already been registered using this IP address.','status.success':'Registration completed!','status.successText':'You can now return to Discord and start using the commands.','status.verified':'Your account is already verified.','status.verifiedText':'You can use the bot commands normally.','status.close':'Close','status.thanks':'Thanks for adding Rikka!','status.thanksText':'Consider joining the support server.'
};
export default en;
