const pt = {
  'nav.logoLabel':'Voltar para a página inicial da Rikka','theme.label':'Tema','sticker.drop':'NOVO DROP!','sticker.wanted':'PROCURANDO ESSA? ♡','sticker.plusOne':'+1 CARTA','sticker.gotIt':'PEGUEI!','rikkaNote.label':'Rikka diz:','rikkaNote.drop':'Será que sua favorita vem no próximo drop? ♡','rikkaNote.collection':'Essa vai pra coleção!',
  'nav.label':'Navegação principal','nav.home':'Início','nav.how':'Como funciona','nav.collection':'Coleção','nav.features':'Recursos','nav.about':'Sobre','nav.login':'Entrar','nav.add':'Adicionar ao Discord','nav.open':'Abrir menu','nav.close':'Fechar menu',
  'lang.label':'Idioma','lang.pt':'Português (Brasil)','lang.en':'English','theme.dark':'Ativar modo escuro','theme.light':'Ativar modo claro','theme.nameLight':'Claro','theme.nameDark':'Escuro','skip':'Pular para o conteúdo',
  'common.ready':'Pronta para começar?','common.add':'Adicionar a Rikka','common.addDiscord':'Adicionar ao Discord','common.support':'Servidor de suporte','common.next':'Sua próxima carta pode estar no próximo drop.','common.nextText':'Adicione a Rikka ao seu servidor e comece sua coleção.','common.cardsNote':'Cartas ilustrativas — artes reais serão exibidas no Discord.','common.avatar':'Avatar oficial da Rikka',
  'home.seo.title':'Rikka — Bot de Coleção de Cartas para Discord','home.seo.description':'Colecione personagens de animes e jogos, encontre diferentes edições e construa sua coleção com a Rikka no Discord.','home.kicker':'Cartas de anime e games no Discord','home.title':'Seus personagens favoritos.','home.accent':'Sua coleção.','home.text':'Encontre personagens de animes e jogos, pegue cartas em drops e monte uma coleção que é só sua — direto no Discord.','home.howCta':'Ver como funciona','home.hello':'Prazer, Rikka!','home.intro':'Um bot de coleção de cartas para Discord.','home.introText':'Escolha seus personagens favoritos, encontre diferentes edições e construa uma coleção única sem sair do seu servidor.','home.dreams':'A Dreams Experience project.','home.dreamsText':'A Rikka nasceu para tornar a coleção de personagens mais divertida dentro do Discord.','home.aboutCta':'Conhecer a Rikka',
  'flow.kicker':'Simples de começar','flow.title':'Como funciona','flow.subtitle':'Do chat para a sua coleção em três passos.','flow.drop':'Drop','flow.dropText':'A Rikka apresenta três cartas no chat.','flow.grab':'Grab','flow.grabText':'Você escolhe a sua antes dos outros.','flow.collection':'Coleção','flow.collectionText':'A carta ganha um lugar na sua coleção.','flow.cta':'Ver como funciona',
  'drop.title':'Um drop aparece.','drop.text':'Três cartas chegam ao canal do Discord. É um pequeno momento de sorte, surpresa e aquela vontade de escolher rápido.','drop.message':'Um novo drop apareceu! Escolha uma carta antes que alguém pegue.','grab.title':'Escolha a sua.','grab.text':'Viu uma carta que combina com sua coleção? Pegue, receba a confirmação e continue de olho no próximo drop.','grab.fast':'Escolha rápida','grab.feedback':'Feedback imediato','grab.message':'Boa escolha! Essa carta agora faz parte da sua coleção.','grab.toast':'Carta B adicionada à coleção','mock.now':'agora','mock.channel':'# drops',
  'collection.kicker':'Sua coleção','collection.title':'Construa sua coleção.','collection.text':'Cada grab conta uma parte da história. Reúna personagens, organize suas cartas favoritas e veja a coleção crescer.','collection.deck':'SEU DECK','collection.unique':'único, do seu jeito','collection.cta':'Conhecer a coleção','collection.card':'Carta','collection.edition':'ED.','editions.kicker':'Mais para descobrir','editions.title':'A mesma personagem.','editions.accent':'Diferentes edições.','editions.text':'Encontre variações, descubra novos visuais e expanda cada parte da sua coleção.','editions.item':'Edição',
  'resources.kicker':'Para completar de verdade','resources.title':'Colecione com intenção.','resources.cta':'Ver recursos','wishlist.label':'Wishlist','wishlist.title':'Encontre as cartas que você realmente quer.','wishlist.text':'Acompanhe personagens e edições desejadas para saber qual será a sua próxima busca.','wishlist.item':'Edição especial','wishlist.state':'Na sua lista','trade.label':'Trades','trade.title':'Troque. Complete. Continue colecionando.','trade.text':'Ofereça cartas, receba outras e chegue mais perto da coleção que você imaginou.','supportTools.label':'Moedas & itens','supportTools.title':'Recursos que ajudam sua coleção.','supportTools.text':'Itens e moedas dão suporte à jornada de colecionar, sem tirar o foco do que importa: as cartas.',
  'how.seo.title':'Como Funciona | Rikka','how.seo.description':'Descubra como os drops, grabs e coleções funcionam na Rikka, um bot de coleção de cartas para Discord.','how.hero.kicker':'A experiência principal','how.hero.title':'Como funciona','how.hero.accent':'Do drop para a sua coleção.','how.hero.text':'A Rikka transforma três passos simples no coração da sua coleção dentro do Discord.','how.cta.title':'Pronto para começar?','how.cta.text':'Adicione a Rikka e espere pelo seu primeiro drop.',
  'collectionPage.seo.title':'Coleção de Cartas | Rikka','collectionPage.seo.description':'Monte sua coleção de personagens, encontre diferentes edições, acompanhe sua wishlist e complete seu deck com a Rikka.','collectionPage.hero.kicker':'Personagens, cartas e edições','collectionPage.hero.title':'Sua coleção.','collectionPage.hero.accent':'Do seu jeito.','collectionPage.hero.text':'Reúna seus personagens favoritos, descubra diferentes edições e veja seu deck crescer a cada grab.','collectionPage.cta.title':'Continue colecionando.','collectionPage.cta.text':'O próximo drop pode trazer exatamente a carta que faltava.',
  'featuresPage.seo.title':'Recursos | Rikka','featuresPage.seo.description':'Conheça wishlist, trades, moedas e itens que ajudam você a completar sua coleção na Rikka.','featuresPage.hero.kicker':'Apoio para cada coleção','featuresPage.hero.title':'Recursos que ajudam','featuresPage.hero.accent':'sua coleção.','featuresPage.hero.text':'Wishlist, trades, moedas e itens deixam sua busca mais organizada sem tirar o foco das cartas.','journey.want':'Deseje','journey.wantText':'Marque o que procura.','journey.trade':'Troque','journey.tradeText':'Faça sua coleção avançar.','journey.complete':'Complete','journey.completeText':'Chegue mais perto do seu deck.',
  'aboutPage.seo.title':'Sobre a Rikka | Bot de Coleção para Discord','aboutPage.seo.description':'Conheça a Rikka, um projeto da Dreams Experience criado para quem gosta de colecionar personagens de animes e jogos no Discord.','aboutPage.hero.kicker':'Sobre a Rikka','aboutPage.hero.title':'Feita para quem gosta','aboutPage.hero.accent':'de colecionar.','aboutPage.hero.text':'Um projeto criado para transformar a coleção de personagens em uma experiência divertida dentro do Discord.','aboutPage.goal':'O objetivo','aboutPage.center':'Cartas no centro de tudo.','aboutPage.p1':'A Rikka é um bot de coleção de cartas de personagens de animes e jogos. Drops, grabs, edições, wishlist e trades existem para tornar cada coleção pessoal e divertida.','aboutPage.p2':'Sem complicar: ela vive no Discord e ajuda você a descobrir, escolher e reunir as cartas que realmente quer.','aboutPage.topgg':'Top.gg','aboutPage.dreamsTitle':'Um projeto Dreams Experience.','aboutPage.dreamsText':'A Rikka faz parte dos projetos da Dreams Experience, mantendo sua própria identidade alegre, colecionável e feita para o Discord.','aboutPage.dreamsCta':'Conhecer a Dreams',
  'footer.tagline':'Cartas, personagens e coleções.','footer.project':'Projeto','footer.legal':'Legal','footer.terms':'Termos','footer.privacy':'Privacidade','footer.soon':'em breve','footer.rights':'Todos os direitos reservados.','footer.dreams':'A Dreams Experience project.',
  'support.seo':'Suporte — Rikka','support.kicker':'Estamos por perto','support.title':'Precisando de ajuda?','support.text':'Entre no servidor de suporte da Rikka e fale diretamente com a equipe do projeto.','support.cta':'Entrar no servidor',
  'notFound.seoTitle':'Página não encontrada | Rikka','notFound.kicker':'Carta perdida','notFound.title':'Essa carta não foi encontrada.','notFound.text':'Parece que você tentou acessar uma página que não existe — ou talvez essa carta tenha escapado da coleção.','notFound.home':'Voltar para o início','notFound.how':'Como funciona','notFound.sticker':'Cadê a carta?','notFound.card':'Carta perdida','notFound.rikka':'Ué... eu tinha certeza que tinha uma carta aqui.','status.notFound':'Página não encontrada ou movida!','status.blocked':'Cadastro bloqueado','status.blockedText':'Já existe uma conta cadastrada usando este endereço de IP.','status.success':'Cadastro realizado com sucesso!','status.successText':'Você já pode retornar ao Discord e começar a usar os comandos.','status.verified':'Sua conta já está verificada.','status.verifiedText':'Você já pode utilizar normalmente os comandos do bot.','status.close':'Fechar','status.thanks':'Obrigado por adicionar a Rikka!','status.thanksText':'Considere entrar no servidor de suporte.'
};
export default pt;
